baseURL: https://dhanteybusiness-blog.netlify.app
languageCode: en-us
title: DARKS ENTERPRISE
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: Darks Enterprise deals in the selling of automobile parts, assembling and dessembling vehicles.
    meta_og_image: C:/Users/dante/Documents/Github/Business-blog/resources/_gen/images/OiP.jpg
    meta_og_title: DARKS ENTERPRISE
    meta_og_type: website 
    meta_og_url:  https://dhanteybusiness-blog.netlify.app
    meta_twitter_creator: '@dhanteybusiness-blog'
    meta_twitter_site: '@dhanteybusiness-blog'
  logo:
    alt: Darks Enterprise
    desktop: images/ky.bmp
    desktop_height: 13px
    desktop_width: 100px
    mobile: images/ky.bmp
    mobile_height: 26px
    mobile_width: 26px
menu:
  main:
    - name: Home
      url: /homepage/
      weight: 1
    - name: Work
      url: /work/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: History
      url: /history/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
